// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pb/sint.proto

package pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Inspired on https://github.com/googleapis/googleapis/blob/master/google/type/date.proto
type Date struct {
	// Year of date. Must be from 1 to 9999, or 0 if specifying a date without
	// a year.
	Year int32 `protobuf:"varint,1,opt,name=year,proto3" json:"year,omitempty"`
	// Month of year. Must be from 1 to 12, or 0 if specifying a year without a
	// month and day.
	Month int32 `protobuf:"varint,2,opt,name=month,proto3" json:"month,omitempty"`
	// Day of month. Must be from 1 to 31 and valid for the year and month, or 0
	// if specifying a year by itself or a year and month where the day is not
	// significant.
	Day                  int32    `protobuf:"varint,3,opt,name=day,proto3" json:"day,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Date) Reset()         { *m = Date{} }
func (m *Date) String() string { return proto.CompactTextString(m) }
func (*Date) ProtoMessage()    {}
func (*Date) Descriptor() ([]byte, []int) {
	return fileDescriptor_c1090064e27192a7, []int{0}
}

func (m *Date) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Date.Unmarshal(m, b)
}
func (m *Date) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Date.Marshal(b, m, deterministic)
}
func (m *Date) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Date.Merge(m, src)
}
func (m *Date) XXX_Size() int {
	return xxx_messageInfo_Date.Size(m)
}
func (m *Date) XXX_DiscardUnknown() {
	xxx_messageInfo_Date.DiscardUnknown(m)
}

var xxx_messageInfo_Date proto.InternalMessageInfo

func (m *Date) GetYear() int32 {
	if m != nil {
		return m.Year
	}
	return 0
}

func (m *Date) GetMonth() int32 {
	if m != nil {
		return m.Month
	}
	return 0
}

func (m *Date) GetDay() int32 {
	if m != nil {
		return m.Day
	}
	return 0
}

type FrequencyRequest struct {
	Visits               []*FrequencyRequest_Visit `protobuf:"bytes,3,rep,name=visits,proto3" json:"visits,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *FrequencyRequest) Reset()         { *m = FrequencyRequest{} }
func (m *FrequencyRequest) String() string { return proto.CompactTextString(m) }
func (*FrequencyRequest) ProtoMessage()    {}
func (*FrequencyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c1090064e27192a7, []int{1}
}

func (m *FrequencyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FrequencyRequest.Unmarshal(m, b)
}
func (m *FrequencyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FrequencyRequest.Marshal(b, m, deterministic)
}
func (m *FrequencyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FrequencyRequest.Merge(m, src)
}
func (m *FrequencyRequest) XXX_Size() int {
	return xxx_messageInfo_FrequencyRequest.Size(m)
}
func (m *FrequencyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FrequencyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FrequencyRequest proto.InternalMessageInfo

func (m *FrequencyRequest) GetVisits() []*FrequencyRequest_Visit {
	if m != nil {
		return m.Visits
	}
	return nil
}

type FrequencyRequest_Visit struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Date                 *Date    `protobuf:"bytes,2,opt,name=date,proto3" json:"date,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FrequencyRequest_Visit) Reset()         { *m = FrequencyRequest_Visit{} }
func (m *FrequencyRequest_Visit) String() string { return proto.CompactTextString(m) }
func (*FrequencyRequest_Visit) ProtoMessage()    {}
func (*FrequencyRequest_Visit) Descriptor() ([]byte, []int) {
	return fileDescriptor_c1090064e27192a7, []int{1, 0}
}

func (m *FrequencyRequest_Visit) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FrequencyRequest_Visit.Unmarshal(m, b)
}
func (m *FrequencyRequest_Visit) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FrequencyRequest_Visit.Marshal(b, m, deterministic)
}
func (m *FrequencyRequest_Visit) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FrequencyRequest_Visit.Merge(m, src)
}
func (m *FrequencyRequest_Visit) XXX_Size() int {
	return xxx_messageInfo_FrequencyRequest_Visit.Size(m)
}
func (m *FrequencyRequest_Visit) XXX_DiscardUnknown() {
	xxx_messageInfo_FrequencyRequest_Visit.DiscardUnknown(m)
}

var xxx_messageInfo_FrequencyRequest_Visit proto.InternalMessageInfo

func (m *FrequencyRequest_Visit) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *FrequencyRequest_Visit) GetDate() *Date {
	if m != nil {
		return m.Date
	}
	return nil
}

type Frequency struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	TimesVisited         uint64   `protobuf:"varint,2,opt,name=timesVisited,proto3" json:"timesVisited,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Frequency) Reset()         { *m = Frequency{} }
func (m *Frequency) String() string { return proto.CompactTextString(m) }
func (*Frequency) ProtoMessage()    {}
func (*Frequency) Descriptor() ([]byte, []int) {
	return fileDescriptor_c1090064e27192a7, []int{2}
}

func (m *Frequency) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Frequency.Unmarshal(m, b)
}
func (m *Frequency) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Frequency.Marshal(b, m, deterministic)
}
func (m *Frequency) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Frequency.Merge(m, src)
}
func (m *Frequency) XXX_Size() int {
	return xxx_messageInfo_Frequency.Size(m)
}
func (m *Frequency) XXX_DiscardUnknown() {
	xxx_messageInfo_Frequency.DiscardUnknown(m)
}

var xxx_messageInfo_Frequency proto.InternalMessageInfo

func (m *Frequency) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Frequency) GetTimesVisited() uint64 {
	if m != nil {
		return m.TimesVisited
	}
	return 0
}

type FrequencyReply struct {
	Frequencies          []*Frequency `protobuf:"bytes,1,rep,name=frequencies,proto3" json:"frequencies,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *FrequencyReply) Reset()         { *m = FrequencyReply{} }
func (m *FrequencyReply) String() string { return proto.CompactTextString(m) }
func (*FrequencyReply) ProtoMessage()    {}
func (*FrequencyReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_c1090064e27192a7, []int{3}
}

func (m *FrequencyReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FrequencyReply.Unmarshal(m, b)
}
func (m *FrequencyReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FrequencyReply.Marshal(b, m, deterministic)
}
func (m *FrequencyReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FrequencyReply.Merge(m, src)
}
func (m *FrequencyReply) XXX_Size() int {
	return xxx_messageInfo_FrequencyReply.Size(m)
}
func (m *FrequencyReply) XXX_DiscardUnknown() {
	xxx_messageInfo_FrequencyReply.DiscardUnknown(m)
}

var xxx_messageInfo_FrequencyReply proto.InternalMessageInfo

func (m *FrequencyReply) GetFrequencies() []*Frequency {
	if m != nil {
		return m.Frequencies
	}
	return nil
}

type FamilyComposition struct {
	Id                   string                     `protobuf:"bytes,3,opt,name=id,proto3" json:"id,omitempty"`
	Children             []*FamilyComposition_Child `protobuf:"bytes,4,rep,name=children,proto3" json:"children,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *FamilyComposition) Reset()         { *m = FamilyComposition{} }
func (m *FamilyComposition) String() string { return proto.CompactTextString(m) }
func (*FamilyComposition) ProtoMessage()    {}
func (*FamilyComposition) Descriptor() ([]byte, []int) {
	return fileDescriptor_c1090064e27192a7, []int{4}
}

func (m *FamilyComposition) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FamilyComposition.Unmarshal(m, b)
}
func (m *FamilyComposition) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FamilyComposition.Marshal(b, m, deterministic)
}
func (m *FamilyComposition) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FamilyComposition.Merge(m, src)
}
func (m *FamilyComposition) XXX_Size() int {
	return xxx_messageInfo_FamilyComposition.Size(m)
}
func (m *FamilyComposition) XXX_DiscardUnknown() {
	xxx_messageInfo_FamilyComposition.DiscardUnknown(m)
}

var xxx_messageInfo_FamilyComposition proto.InternalMessageInfo

func (m *FamilyComposition) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *FamilyComposition) GetChildren() []*FamilyComposition_Child {
	if m != nil {
		return m.Children
	}
	return nil
}

type FamilyComposition_Child struct {
	Age                  uint32   `protobuf:"varint,1,opt,name=age,proto3" json:"age,omitempty"`
	Gender               string   `protobuf:"bytes,2,opt,name=gender,proto3" json:"gender,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FamilyComposition_Child) Reset()         { *m = FamilyComposition_Child{} }
func (m *FamilyComposition_Child) String() string { return proto.CompactTextString(m) }
func (*FamilyComposition_Child) ProtoMessage()    {}
func (*FamilyComposition_Child) Descriptor() ([]byte, []int) {
	return fileDescriptor_c1090064e27192a7, []int{4, 0}
}

func (m *FamilyComposition_Child) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FamilyComposition_Child.Unmarshal(m, b)
}
func (m *FamilyComposition_Child) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FamilyComposition_Child.Marshal(b, m, deterministic)
}
func (m *FamilyComposition_Child) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FamilyComposition_Child.Merge(m, src)
}
func (m *FamilyComposition_Child) XXX_Size() int {
	return xxx_messageInfo_FamilyComposition_Child.Size(m)
}
func (m *FamilyComposition_Child) XXX_DiscardUnknown() {
	xxx_messageInfo_FamilyComposition_Child.DiscardUnknown(m)
}

var xxx_messageInfo_FamilyComposition_Child proto.InternalMessageInfo

func (m *FamilyComposition_Child) GetAge() uint32 {
	if m != nil {
		return m.Age
	}
	return 0
}

func (m *FamilyComposition_Child) GetGender() string {
	if m != nil {
		return m.Gender
	}
	return ""
}

type ChildrenCountRequest struct {
	FamilyCompositions   []*FamilyComposition `protobuf:"bytes,1,rep,name=familyCompositions,proto3" json:"familyCompositions,omitempty"`
	Frequency            []*Frequency         `protobuf:"bytes,2,rep,name=frequency,proto3" json:"frequency,omitempty"`
	FrequencyThreshold   uint64               `protobuf:"varint,3,opt,name=frequencyThreshold,proto3" json:"frequencyThreshold,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *ChildrenCountRequest) Reset()         { *m = ChildrenCountRequest{} }
func (m *ChildrenCountRequest) String() string { return proto.CompactTextString(m) }
func (*ChildrenCountRequest) ProtoMessage()    {}
func (*ChildrenCountRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c1090064e27192a7, []int{5}
}

func (m *ChildrenCountRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChildrenCountRequest.Unmarshal(m, b)
}
func (m *ChildrenCountRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChildrenCountRequest.Marshal(b, m, deterministic)
}
func (m *ChildrenCountRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChildrenCountRequest.Merge(m, src)
}
func (m *ChildrenCountRequest) XXX_Size() int {
	return xxx_messageInfo_ChildrenCountRequest.Size(m)
}
func (m *ChildrenCountRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ChildrenCountRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ChildrenCountRequest proto.InternalMessageInfo

func (m *ChildrenCountRequest) GetFamilyCompositions() []*FamilyComposition {
	if m != nil {
		return m.FamilyCompositions
	}
	return nil
}

func (m *ChildrenCountRequest) GetFrequency() []*Frequency {
	if m != nil {
		return m.Frequency
	}
	return nil
}

func (m *ChildrenCountRequest) GetFrequencyThreshold() uint64 {
	if m != nil {
		return m.FrequencyThreshold
	}
	return 0
}

type ChildrenCountReply struct {
	Counts               []*ChildrenCountReply_Count `protobuf:"bytes,4,rep,name=counts,proto3" json:"counts,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                    `json:"-"`
	XXX_unrecognized     []byte                      `json:"-"`
	XXX_sizecache        int32                       `json:"-"`
}

func (m *ChildrenCountReply) Reset()         { *m = ChildrenCountReply{} }
func (m *ChildrenCountReply) String() string { return proto.CompactTextString(m) }
func (*ChildrenCountReply) ProtoMessage()    {}
func (*ChildrenCountReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_c1090064e27192a7, []int{6}
}

func (m *ChildrenCountReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChildrenCountReply.Unmarshal(m, b)
}
func (m *ChildrenCountReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChildrenCountReply.Marshal(b, m, deterministic)
}
func (m *ChildrenCountReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChildrenCountReply.Merge(m, src)
}
func (m *ChildrenCountReply) XXX_Size() int {
	return xxx_messageInfo_ChildrenCountReply.Size(m)
}
func (m *ChildrenCountReply) XXX_DiscardUnknown() {
	xxx_messageInfo_ChildrenCountReply.DiscardUnknown(m)
}

var xxx_messageInfo_ChildrenCountReply proto.InternalMessageInfo

func (m *ChildrenCountReply) GetCounts() []*ChildrenCountReply_Count {
	if m != nil {
		return m.Counts
	}
	return nil
}

type ChildrenCountReply_Count struct {
	Age                  uint32   `protobuf:"varint,1,opt,name=age,proto3" json:"age,omitempty"`
	Gender               string   `protobuf:"bytes,2,opt,name=gender,proto3" json:"gender,omitempty"`
	Count                uint64   `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChildrenCountReply_Count) Reset()         { *m = ChildrenCountReply_Count{} }
func (m *ChildrenCountReply_Count) String() string { return proto.CompactTextString(m) }
func (*ChildrenCountReply_Count) ProtoMessage()    {}
func (*ChildrenCountReply_Count) Descriptor() ([]byte, []int) {
	return fileDescriptor_c1090064e27192a7, []int{6, 0}
}

func (m *ChildrenCountReply_Count) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChildrenCountReply_Count.Unmarshal(m, b)
}
func (m *ChildrenCountReply_Count) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChildrenCountReply_Count.Marshal(b, m, deterministic)
}
func (m *ChildrenCountReply_Count) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChildrenCountReply_Count.Merge(m, src)
}
func (m *ChildrenCountReply_Count) XXX_Size() int {
	return xxx_messageInfo_ChildrenCountReply_Count.Size(m)
}
func (m *ChildrenCountReply_Count) XXX_DiscardUnknown() {
	xxx_messageInfo_ChildrenCountReply_Count.DiscardUnknown(m)
}

var xxx_messageInfo_ChildrenCountReply_Count proto.InternalMessageInfo

func (m *ChildrenCountReply_Count) GetAge() uint32 {
	if m != nil {
		return m.Age
	}
	return 0
}

func (m *ChildrenCountReply_Count) GetGender() string {
	if m != nil {
		return m.Gender
	}
	return ""
}

func (m *ChildrenCountReply_Count) GetCount() uint64 {
	if m != nil {
		return m.Count
	}
	return 0
}

func init() {
	proto.RegisterType((*Date)(nil), "sint.Date")
	proto.RegisterType((*FrequencyRequest)(nil), "sint.FrequencyRequest")
	proto.RegisterType((*FrequencyRequest_Visit)(nil), "sint.FrequencyRequest.Visit")
	proto.RegisterType((*Frequency)(nil), "sint.Frequency")
	proto.RegisterType((*FrequencyReply)(nil), "sint.FrequencyReply")
	proto.RegisterType((*FamilyComposition)(nil), "sint.FamilyComposition")
	proto.RegisterType((*FamilyComposition_Child)(nil), "sint.FamilyComposition.Child")
	proto.RegisterType((*ChildrenCountRequest)(nil), "sint.ChildrenCountRequest")
	proto.RegisterType((*ChildrenCountReply)(nil), "sint.ChildrenCountReply")
	proto.RegisterType((*ChildrenCountReply_Count)(nil), "sint.ChildrenCountReply.Count")
}

func init() { proto.RegisterFile("pb/sint.proto", fileDescriptor_c1090064e27192a7) }

var fileDescriptor_c1090064e27192a7 = []byte{
	// 467 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x53, 0x4d, 0x6f, 0xd3, 0x40,
	0x10, 0xad, 0xed, 0x75, 0x44, 0xa6, 0x1f, 0x84, 0x51, 0x54, 0x2c, 0x0b, 0xaa, 0x6a, 0x4f, 0xbd,
	0x60, 0xd4, 0x80, 0x40, 0x5c, 0x40, 0xaa, 0x51, 0x23, 0x71, 0x5c, 0x10, 0x07, 0x6e, 0x4e, 0xbc,
	0x6d, 0x56, 0x72, 0x6c, 0xe3, 0xdd, 0x22, 0xf9, 0xc8, 0x4f, 0x00, 0x89, 0xbf, 0xc3, 0x6f, 0x43,
	0x3b, 0xde, 0xa4, 0xad, 0xe3, 0x4a, 0x9c, 0x32, 0xf3, 0xf2, 0xe6, 0xed, 0x7b, 0xb3, 0x5e, 0x38,
	0xac, 0x17, 0x2f, 0xb5, 0x2a, 0x4d, 0x52, 0x37, 0x95, 0xa9, 0x90, 0xd9, 0x9a, 0x5f, 0x00, 0xfb,
	0x98, 0x19, 0x89, 0x08, 0xac, 0x95, 0x59, 0x13, 0x79, 0xa7, 0xde, 0x59, 0x28, 0xa8, 0xc6, 0x29,
	0x84, 0xeb, 0xaa, 0x34, 0xab, 0xc8, 0x27, 0xb0, 0x6b, 0x70, 0x02, 0x41, 0x9e, 0xb5, 0x51, 0x40,
	0x98, 0x2d, 0xf9, 0x4f, 0x0f, 0x26, 0x97, 0x8d, 0xfc, 0x7e, 0x23, 0xcb, 0x65, 0x2b, 0xec, 0xaf,
	0x36, 0xf8, 0x1a, 0x46, 0x3f, 0x94, 0x56, 0x46, 0x47, 0xc1, 0x69, 0x70, 0xb6, 0x3f, 0x7b, 0x96,
	0xd0, 0xd9, 0x7d, 0x5e, 0xf2, 0xd5, 0x92, 0x84, 0xe3, 0xc6, 0x6f, 0x21, 0x24, 0x00, 0x8f, 0xc0,
	0x57, 0x39, 0xb9, 0x19, 0x0b, 0x5f, 0xe5, 0x78, 0x02, 0x2c, 0xcf, 0x8c, 0x24, 0x2b, 0xfb, 0x33,
	0xe8, 0xc4, 0xac, 0x73, 0x41, 0x38, 0xff, 0x00, 0xe3, 0xad, 0xf4, 0xce, 0x30, 0x87, 0x03, 0xa3,
	0xd6, 0x52, 0x93, 0xb4, 0xcc, 0x49, 0x84, 0x89, 0x7b, 0x18, 0x4f, 0xe1, 0xe8, 0x8e, 0xb7, 0xba,
	0x68, 0xf1, 0x1c, 0xf6, 0xaf, 0x1c, 0xa2, 0xa4, 0x8e, 0x3c, 0x8a, 0xf1, 0xb8, 0x1f, 0xe3, 0x2e,
	0x87, 0xff, 0xf2, 0xe0, 0xc9, 0x65, 0xb6, 0x56, 0x45, 0x9b, 0x56, 0xeb, 0xba, 0xd2, 0xca, 0xa8,
	0xaa, 0x74, 0x76, 0x82, 0xad, 0x9d, 0x77, 0xf0, 0x68, 0xb9, 0x52, 0x45, 0xde, 0xc8, 0x32, 0x62,
	0xa4, 0xfa, 0xdc, 0xa9, 0xf6, 0x47, 0x93, 0xd4, 0xf2, 0xc4, 0x96, 0x1e, 0x9f, 0x43, 0x48, 0x90,
	0xbd, 0x85, 0xec, 0x5a, 0x52, 0xc6, 0x43, 0x61, 0x4b, 0x3c, 0x86, 0xd1, 0xb5, 0x2c, 0x73, 0xd9,
	0x50, 0xbc, 0xb1, 0x70, 0x1d, 0xff, 0xeb, 0xc1, 0x34, 0x75, 0xf3, 0x69, 0x75, 0x53, 0x9a, 0xcd,
	0x0d, 0xcd, 0x01, 0xaf, 0xfa, 0x07, 0x6e, 0x62, 0x3e, 0x7d, 0xc0, 0x90, 0x18, 0x18, 0xc1, 0x17,
	0x30, 0xde, 0x2c, 0xa1, 0x8d, 0xfc, 0xe1, 0x35, 0xdd, 0x32, 0x30, 0x01, 0xdc, 0x36, 0x5f, 0x56,
	0x8d, 0xd4, 0xab, 0xaa, 0xe8, 0xd6, 0xc3, 0xc4, 0xc0, 0x3f, 0xfc, 0x8f, 0x07, 0xd8, 0x0b, 0x60,
	0xaf, 0xe7, 0x0d, 0x8c, 0x96, 0xb6, 0xd3, 0x6e, 0x87, 0x27, 0xdd, 0x91, 0xbb, 0xcc, 0xa4, 0x2b,
	0x1d, 0x3b, 0x9e, 0x43, 0x48, 0xc0, 0xff, 0xaf, 0xd0, 0x3e, 0x04, 0x1a, 0x76, 0x26, 0xbb, 0x66,
	0xf6, 0xdb, 0x03, 0xf6, 0x59, 0x95, 0x06, 0xdf, 0xc3, 0xc1, 0x5c, 0x9a, 0xdb, 0xcf, 0xef, 0x78,
	0xf8, 0x53, 0x8f, 0xa7, 0x3b, 0x78, 0x5d, 0xb4, 0x7c, 0x0f, 0x3f, 0xc1, 0x64, 0x2e, 0xcd, 0x3d,
	0xe3, 0x18, 0x0f, 0xa6, 0xe9, 0x74, 0xa2, 0x87, 0x92, 0xf2, 0xbd, 0x0b, 0xf6, 0xcd, 0xaf, 0x17,
	0x8b, 0x11, 0x3d, 0xf1, 0x57, 0xff, 0x02, 0x00, 0x00, 0xff, 0xff, 0x37, 0x92, 0x75, 0x81, 0xf3,
	0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// SintClient is the client API for Sint service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SintClient interface {
	GetFrequency(ctx context.Context, in *FrequencyRequest, opts ...grpc.CallOption) (*FrequencyReply, error)
	GetChildrenCount(ctx context.Context, in *ChildrenCountRequest, opts ...grpc.CallOption) (*ChildrenCountReply, error)
}

type sintClient struct {
	cc *grpc.ClientConn
}

func NewSintClient(cc *grpc.ClientConn) SintClient {
	return &sintClient{cc}
}

func (c *sintClient) GetFrequency(ctx context.Context, in *FrequencyRequest, opts ...grpc.CallOption) (*FrequencyReply, error) {
	out := new(FrequencyReply)
	err := c.cc.Invoke(ctx, "/sint.Sint/GetFrequency", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sintClient) GetChildrenCount(ctx context.Context, in *ChildrenCountRequest, opts ...grpc.CallOption) (*ChildrenCountReply, error) {
	out := new(ChildrenCountReply)
	err := c.cc.Invoke(ctx, "/sint.Sint/GetChildrenCount", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SintServer is the server API for Sint service.
type SintServer interface {
	GetFrequency(context.Context, *FrequencyRequest) (*FrequencyReply, error)
	GetChildrenCount(context.Context, *ChildrenCountRequest) (*ChildrenCountReply, error)
}

// UnimplementedSintServer can be embedded to have forward compatible implementations.
type UnimplementedSintServer struct {
}

func (*UnimplementedSintServer) GetFrequency(ctx context.Context, req *FrequencyRequest) (*FrequencyReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFrequency not implemented")
}
func (*UnimplementedSintServer) GetChildrenCount(ctx context.Context, req *ChildrenCountRequest) (*ChildrenCountReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetChildrenCount not implemented")
}

func RegisterSintServer(s *grpc.Server, srv SintServer) {
	s.RegisterService(&_Sint_serviceDesc, srv)
}

func _Sint_GetFrequency_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FrequencyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SintServer).GetFrequency(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sint.Sint/GetFrequency",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SintServer).GetFrequency(ctx, req.(*FrequencyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Sint_GetChildrenCount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChildrenCountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SintServer).GetChildrenCount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sint.Sint/GetChildrenCount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SintServer).GetChildrenCount(ctx, req.(*ChildrenCountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Sint_serviceDesc = grpc.ServiceDesc{
	ServiceName: "sint.Sint",
	HandlerType: (*SintServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetFrequency",
			Handler:    _Sint_GetFrequency_Handler,
		},
		{
			MethodName: "GetChildrenCount",
			Handler:    _Sint_GetChildrenCount_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pb/sint.proto",
}
